version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_PASS:
    secure: 2zGJE9haG3rnIgDPVHvvMQ==

init:
  - ps: Remove-Item -Recurse -Force C:/cygwin
  - ps: Remove-Item -Recurse -Force C:/cygwin64

install:
  - docker version

build_script:
  - "docker build -t keneanung/qt-windows:5.13.0-mingw-x86 ."
  - docker login -u keneanung -p "%DOCKER_PASS%"
  - "docker push keneanung/qt-windows:5.13.0-mingw-x86"