version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: 7sx6XN+jecSIGZeZBZURmtM/mbifGaMYP1vVf8TwRFI=
  DOCKER_PASS:
    secure: 2zGJE9haG3rnIgDPVHvvMQ==

install:
  - docker version

build_script:
  - "docker build -t keneanung/qt-windows:latest -t keneanung/qt-windows:5.12.2 ."
  - docker login -u %DOCKER_USER% -p %DOCKER_PASS%
  - "docker push keneanung/qt-windows:5.12.2"
  - "docker push keneanung/qt-windows:latest"