version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: 7sx6XN+jecSIGZeZBZURmtM/mbifGaMYP1vVf8TwRFI=
  DOCKER_PASS:
    secure: 2zGJE9haG3rnIgDPVHvvMQ==

install:
  - docker version

build_script:
  - "docker build -t keneanung/qt-windows:5.12.2-mingw-x86 ."
  - echo %DOCKER_PASS% | docker login -u "%DOCKER_USER%" --password-stdin
  - "docker push keneanung/qt-windows:5.12.2-mingw-x86"